/* Generated by Yosys 0.48+0 (git sha1 e91e95f501bef4799b1e07df67de8032d92bad07, g++ 14.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

(* top =  1  *)
(* src = "andGate.v:1.1-3.10" *)
module and_gate(a, b, y);
  (* src = "andGate.v:1.23-1.24" *)
  input a;
  wire a;
  (* src = "andGate.v:1.32-1.33" *)
  input b;
  wire b;
  (* src = "andGate.v:1.42-1.43" *)
  output y;
  wire y;
  assign y = b & a;
endmodule
